---
services:
  docuseal:
    container_name: docuseal
    image: docuseal/docuseal:2.1.0
    ports:
      - 10.0.0.1:3030:3000
    volumes:
      - ./data-docuseal:/data
    restart: unless-stopped
networks: {}
...
